### ISSUE TITLE
E-Mail-Adressen entfernen

### ISSUE THREAD

**Issue by acidicX** [eXDigital/ex-dev#2]
Servus,

ihr habt alle Studentendaten inkl. der E-Mail-Adressen in das Repo geladen (`public/data/alumni_data_avatar_id.csv`). Das ist wegen Spammern in einem öffentlichen Repo nicht ganz so cool ;-) außerdem ist es ein Datenschutzverstoß und kostet richtig Kohle, wenn das jemand anzeigt. Durch die History im git lässt sich das nicht ganz so einfach löschen, es gibt aber Tools dafür.

@jannikkeye https://help.github.com/articles/remove-sensitive-data/

**Comment by acidicX** [comment]
Als Notiz noch: man kann die Files in /public auch direkt auf der ex-Seite abrufen, vergesst also nicht, das neue Build auch auf den Server zu schieben.

Außerdem kenne ich jetzt noch ein bissl mehr, z.B. SMTP-Server-Daten... ;-)

**Comment by jannikkeye** [comment]
Die Daten sollten jetzt aus der ganzen history gelöscht sein. Guter Punkt, an sowas hat gar keiner bei uns gedacht. 
Auch gleich aufn server gepullt.
Wieder was fürs nächste mal gelernt.
Danke dir!
